apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
    tier: database
spec:
  selector:
    app: mysql
    tier: database
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  #type: ClusterIP
  clusterIP: None  # We Use DNS, Thus ClusterIP is not relevant
