apiVersion: v1
kind: Service # Kubernetes resource kind we are creating
metadata:
  name: demo-spa-blue-green-service
  namespace: default
  labels:
    service-label-key: demo-spa-blue-green-service-label
spec:
  # type: ClusterIP
  type: NodePort # type of service
  ports:
  - name: demo-blue-green-service-port
    protocol: TCP
    port: 80 # The port exposed ouside the cluster by service
    targetPort: 8000 # Port exposed by Pod
    nodePort: 31000 # Optional: By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
  selector:
    app: demo # pod with label demo say to which Pods this Service provide access


