apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-adapter-deployment
spec:
  selector:
    matchLabels:
      app: my-adapter-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-adapter-app
    spec:
      containers:
      - name: my-microservice
        image: my-microservice-image:latest
        ports:
        - containerPort: 80
      - name: my-adapter
        image: my-adapter-image:latest
        ports:
        - containerPort: 8080
