apiVersion: v1
kind: Service # Kubernetes resource kind we are creating
metadata:
  name: test-spa-service
  namespace: default
  labels:
    service-label-key: test-spa-service-label
spec:
  # type: ClusterIP
  type: NodePort # type of service
  ports:
  - name: test-service-port
    protocol: TCP
    port: 80 # The port exposed ouside the cluster by service
    targetPort: 8080 # Port exposed by Pod
    #targetPort: test-spa-port # you can also use name to refer the pods port
    nodePort: 31500 # Optional: By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
  selector:
    app: test # pod with label test say to which Pods this Service provide access


