apiVersion: v1
kind: Service # Kubernetes resource kind we are creating
metadata:
  name: demo-spa-clusterip-service
  namespace: default
  labels:
    service-label-key: demo-spa-service-clusterip-label
spec:
  type: ClusterIP
  ports:
  - name: demo-service-port
    protocol: TCP
    port: 8001 # The port exposed ouside the cluster by service
    targetPort: 8000 # Port exposed by Pod
    #targetPort: demo-spa-port # you can also use name to refer the pods port
  selector:
    app: demo # pod with label demo say to which Pods this Service provide access


