apiVersion: networking.k8s.io/v1
kind: Ingress # Kubernetes resource kind we are creating
metadata:
  name: spa-ingress
  namespace: default
  labels:
    service-label-key: spa-ingress-label
spec:
  rules:
  - host: demo.k8s.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-spa-clusterip-service
            port:
              number: 8001
  - host: test.k8s.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test-spa-clusterip-service
            port:
              number: 8002
