# https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/annotations/
apiVersion: v1a
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo-nlb-service
  name: demo-nlb-service
  namespace: demo-nlb
  annotations:
    # Note that the backend talks over HTTP.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # TODO: Fill in with the ARN of your certificate.
    #service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ${CERTIFICATE_ARN}
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
    service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true
    #service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-xxxx, mySubnet
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
    - name: https
      port: 443
      targetPort: 8000
  selector:
    app: demo
status:
  loadBalancer: {}