apiVersion: v1
kind: Service # Kubernetes resource kind we are creating
metadata:
  name: demo-spa-service
  namespace: default
  labels:
    service-label-key: demo-spa-service-label
spec:
  ports:
  - name: demo-service-port
    protocol: TCP
    port: 80 # The port exposed ouside the cluster by service
    targetPort: 8000 # Port exposed by Pod
  selector:
    app: demo # pod with label demo say to which Pods this Service provide access


