apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: my-targetgroup-binding
  namespace: my-app
spec:
  targetGroupARN: arn:aws:elasticloadbalancing:us-west-2:123456789012:targetgroup/my-targetgroup/abcdef1234567890
  serviceRef:
    name: my-gateway
    port: 8080
    namespace: my-app
  targetType: ip
  virtualGatewayRef:
    name: my-gateway
    namespace: my-app
