apiVersion: networking.k8s.io/v1
kind: Ingress # Kubernetes resource kind we are creating
metadata:
  name: spa-canary-ingress
  namespace: default
  labels:
    service-label-key: spa-canary-ingress-label
  annotations:
    #kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/canary: "true"
    #nginx.ingress.kubernetes.io/canary-by-header: "canary"
    nginx.ingress.kubernetes.io/canary-weight: "20"
spec:
  rules:
  - host: demo.k8s.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-spa-canary-service
            port:
              number: 8001
     # - path: /
     #   pathType: Prefix
     #   backend:
     #     service:
     #       name: demo-spa-stable
     #       port:
     #         number: 8001
