apiVersion: networking.k8s.io/v1
kind: Ingress # Kubernetes resource kind we are creating
metadata:
  name: spa-stable-ingress
  namespace: default
  labels:
    service-label-key: spa-stable-ingress-label
  annotations:
    #kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: demo.k8s.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-spa-stable-service
            port:
              number: 8001

